### ISSUE TITLE
Minor bug when running on 10.14

### ISSUE THREAD

**Issue by Honestpuck** [jamf/CIS-for-macOS-High-Sierra-CP#2]
In both 2_Security_Audit_Compliance scripts when checking "5.14 Ensure system is set to hibernate" the line that sets hibernateValue causes an error on Mojave 10.14.

`hibernateValue=$(pmset -g | egrep standbydelay  | awk '{print $2}')`

This is because `pmset -g` now returns `standbydelaylow` and `standbydelayhigh`

It can be fixed by changing the line to

`hibernateValue=$(pmset -g | egrep -e "standbydelay " -e standbydelaylow | awk '{print $2}')`

The line above works on 10.13 and 10.14

**Comment by krypted** [comment]
Done. Thanks, Tony.
